[package]
name = "coinbase-pro-rs"
version = "0.2.5"
authors = ["ae <inv2004@gmail.com>"]
repository = "https://github.com/inv2004/coinbase-pro-rs"
description = "Coinbase pro client for Rust"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "api-bindings" ]
keywords = [ "exchange", "coinbase", "bitcoin", "websocket" ]

[dependencies]
failure = "0.1.2"
hyper = "0.12.10"
hyper-tls = "0.3.0"
serde = "1.0.79"
serde_json = "1.0.30"
serde_derive = "1.0.79"
tokio = "0.1.8"
futures = "0.1.23"
base64 = "0.9.3"
hmac = "0.6.3"
sha2 = "0.7.1"
uuid = { version = "0.7.1", features = [ "serde", "v4" ] }
log = "0.4.4"
pretty_env_logger = "0.2.4"
chrono = { version = "0.4.5", features = [ "serde" ] }
time = "0.1.40"
tokio-tungstenite = "0.6.0"
url = "1.7.1"
