[package]
name = "coinbase-pro-rs"
version = "0.2.9"
authors = ["ae <inv2004@gmail.com>"]
repository = "https://github.com/inv2004/coinbase-pro-rs"
description = "Coinbase pro client for Rust"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "api-bindings" ]
keywords = [ "exchange", "coinbase", "bitcoin", "websocket" ]

[dependencies]
failure = "0.1.5"
hyper = "0.12.20"
hyper-tls = "0.3.0"
serde = "1.0.84"
serde_json = "1.0.34"
serde_derive = "1.0.84"
tokio = "0.1.8"
futures = "0.1.23"
base64 = "0.10.0"
hmac = "0.7.0"
sha2 = "0.8.0"
uuid = { version = "0.7.1", features = [ "serde", "v4" ] }
log = "0.4.4"
pretty_env_logger = "0.3.0"
chrono = { version = "0.4.5", features = [ "serde" ] }
time = "0.1.41"
tokio-tungstenite = "0.6.0"
url = "1.7.1"
