[package]
name = "coinbase-pro-rs"
version = "0.1.0"
authors = ["unknown <inv2004@gmail.com>"]
description = "Coinbase pro client for Rust"
license = "MIT/Apache-2.0"

[dependencies]
failure = "*"
hyper = "*"
hyper-tls = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
tokio = "*"
futures = "0.1.21"
base64 = "*"
hmac = "*"
sha2 = "*"
uuid = { version = "*", features = [ "serde", "v4" ] }
log = "*"
pretty_env_logger = "*"
chrono = { version = "*", features = [ "serde" ] }
time = "*"

